/**
    Generator for Ninja build scripts

    License: Subject to the terms of the MIT license
    Authors: Hariprakash V
*/
module dub.generators.ninja;

import dub.generators.generator;
import dub.project;

class NinjaGenerator : ProjectGenerator
{
    this(Project project)
    {
        super(project);
    }

    override void generateTargets(GeneratorSettings settings, in TargetInfo[string] targets)
    {
        import std.stdio : File;
        import std.path : baseName, stripExtension;

        auto f = File("build.ninja", "w");
        f.writeln("# Generated by DUB ninja generator");
        f.writeln();
        f.writeln("rule dc");
        f.writeln("  command = ", settings.platform.compilerBinary, " $flags -c $in -of=$out");
        f.writeln("  description = Compiling $in");
        f.writeln();
        foreach (name, info; targets)
        {
            foreach (src; info.buildSettings.sourceFiles)
            {
                import std.array : replace;
                auto obj = stripExtension(src).replace("/", "_").replace(":", "_") ~ ".o";
                f.writeln("build ", obj, ": dc ", src);
            }
            f.writeln();
        }
        //foreach (name, info; targets)
        //f.writeln("default ", info.buildSettings.targetName);
        f.close();
    }
}