/**
    Generator for Ninja build scripts

    License: Subject to the terms of the MIT license
    Authors: Hariprakash V
*/
module dub.generators.ninja;

import dub.generators.generator;
import dub.project;

class NinjaGenerator : ProjectGenerator
{
    this(Project project)
    {
        super(project);
    }

    override void generateTargets(GeneratorSettings settings, in TargetInfo[string] targets)
    {
        import std.stdio : File;
        import std.file : mkdirRecurse;

        auto outputPath = settings.buildSettings.targetPath;
        auto f = File("build.ninja", "w");
        f.writeln("# Generated by DUB ninja generator");
        f.close();
    }
}